# MerMer Default Config

title = "TitanExplorer"

[base]
folder = "TitanExplorer"
static = "./build/frontend/"
debug = false

[blockchain]
type = "cafeca"

[database]
type = "firebase"

[api]
pathname = [
  "get | /,/version | Static.Utils.readPackageInfo"
]
